import React from "react";

import "./loader.css";

/* generated by https://loading.io/ */
const Loader = () => {
  return (
    <div className="loader">
      <div className="loader-spinner">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  );
};

export default Loader;
